# Generated by Django 4.0 on 2021-12-25 16:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.UUIDField()),
                ('session_name', models.CharField(max_length=255)),
                ('recorded_on', models.DateTimeField(auto_now_add=True)),
                ('duration_in_seconds', models.FloatField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
