# Generated by Django 4.0 on 2021-12-26 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('content_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='count', to='contenttypes.contenttype')),
            ],
        ),
    ]
