# Generated by Django 4.0 on 2021-12-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_alter_session_recorded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='recorded_on',
            field=models.DateTimeField(),
        ),
    ]
