# Generated by Django 4.0 on 2021-12-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_alter_session_recorded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='recorded_on',
            field=models.DateTimeField(db_index=True),
        ),
    ]
